before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: ds-operator
    goos:
      - linux
    goarch:
      - amd64
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    builds:
      - ds-operator
    image_templates:
      - "{{.Env.IMG}}"
    dockerfile: build/Dockerfile
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
archives:
  - replacements:
      linux: Linux

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: ForgeRock
    name: ds-operator
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
