# Note: We just use a vanilla docker build trigger in cloudbuild.yaml - so this file is 
# not currently used.
# This can be fleshed out later if we want to use a more complex trigger.
# Cloudbuild just builds the docker image. The release yaml is produced by a github action
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ds-operator:$TAG_NAME', '.']
images:
- gcr.io/$PROJECT_ID/ds-operator:$TAG_NAME