
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-directory-forgerock-com-forgerock-com-v1alpha1-directoryservice
  failurePolicy: Fail
  name: mdirectoryservice.kb.io
  rules:
  - apiGroups:
    - directory.forgerock.com.forgerock.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - directoryservices

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-directory-forgerock-com-forgerock-com-v1alpha1-directoryservice
  failurePolicy: Fail
  name: vdirectoryservice.kb.io
  rules:
  - apiGroups:
    - directory.forgerock.com.forgerock.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - directoryservices
