#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || (echo "Couldn't determine the root path" ; exit 1)


# Default these values from the users configuration
PROJECT_ID=$(gcloud config list --format 'value(core.project)')
PROJECT=${PROJECT:-$PROJECT_ID}


# shellcheck source=tests/bin/cluster-opts.sh
. $SCRIPT_DIR/cluster-opts.sh
R=$(gcloud config list --format 'value(compute.region)')
REGION=${REGION:-$R}

ZONE=${ZONE:-"$REGION-a"}

echo "Getting the cluster credentials for $NAME in Zone $ZONE"
gcloud container clusters get-credentials "$NAME" --zone "$ZONE" || exit 1

echo "***Draining all nodes***"
kubectl cordon -l forgerock.io/cluster
kubectl delete pod --all-namespaces --all --grace-period=0
echo
echo "***Deleting all PVCs***"
kubectl delete pvc --all-namespaces --all

# Attempt to release any L4 service load balancers
echo
echo "***Cleaning all services and load balancers if any***"
kubectl delete svc --all --all-namespaces

# Delete the cluster. Defaults to the current project.
gcloud container clusters delete --quiet "$NAME" --zone "$ZONE"


echo "Check your GCP console for any orphaned project resources such as disks!"
