{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ds-operator.fullname" . }}-leader-election-role
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ds-operator.fullname" . }}-directorybackup-editor-role
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ds-operator.fullname" . }}-directoryrestore-editor-role
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ds-operator.fullname" . }}-directoryservice-editor-role
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ds-operator.fullname" . }}-manager-role
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  - secrets/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - delete
  - get
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackup
  - directoryrestore
  - directoryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackup/status
  - directoryrestore/status
  - directoryservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/finalizers
  verbs:
  - '*'
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/finalizers
  verbs:
  - '*'
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices/finalizers
  verbs:
  - '*'
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ds-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ds-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ds-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ds-operator.fullname" . }}-directorybackup-editor-rolebinding
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ds-operator.fullname" . }}-directorybackup-editor-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ds-operator.fullname" . }}-directoryrestore-editor-rolebinding
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ds-operator.fullname" . }}-directoryrestore-editor-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ds-operator.fullname" . }}-directoryservice-editor-rolebinding
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ds-operator.fullname" . }}-directoryservice-editor-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ds-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "ds-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ds-operator.fullname" . }}-manager-role
  name: ds-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "ds-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
