# permissions for end users to edit directorybackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directorybackup-editor-role
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/status
  verbs:
  - get
