# permissions for end users to edit directoryservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directoryservice-editor-role
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices/status
  verbs:
  - get
