# permissions for end users to edit directoryrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directoryrestore-editor-role
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/status
  verbs:
  - get
