# permissions for end users to view directoryrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directoryrestore-viewer-role
rules:
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/status
  verbs:
  - get
