
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - jobs/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/finalizers
  verbs:
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directorybackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/finalizers
  verbs:
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryrestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.forgerock.io
  resources:
  - directoryservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
