# Backup the directory to a PVC
apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryBackup
metadata:
  name: ds-backup
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  # The pod template is exactly the same as the one used for the DirectoryService CRD
  # In this case, it applies to the DS Job that will run the backup.
  # The "backup" entrypoint will be called.
  podTemplate:
    image:  gcr.io/forgeops-public/ds:7.2-dev
    imagePullPolicy: IfNotPresent

    # The spec for the volume that holds the backup. The volume name will be the same as our metadata.name (ds-backup in this case)
    volumeClaimSpec:
      storageClassName: fast
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 512Mi

    # Used for snapshot creation
    volumeSnapshotClassName: ds-snapshot-class

    # Backup / Restore need the master keypair for encrypting/decrypting data.
    secrets:
      masterSecretName: ds-master-keypair
      sslSecretName: ds-ssl-keypair
      truststoreSecretName: ds-ssl-keypair
    # The backup/restore default scripts support different backup types
    # The sample below runs all three backups in sequence.
    env:
    - name: DS_BACKUP_TYPE
      value: "tar,ldif,dsbackup"


  # The directory pvc to target for backup. This can be a "live" ds instance,
  # assuming your snapshot provider can take "crash consistent" snapshots
  claimToBackup: data-ds-idrepo-0