apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryBackup
metadata:
  name: ds-backup
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  backupPVC:
    name: ds-backup-pvc
    storageClassName: csi-hostpath-sc
    size: 1Gi

  # Backup in ldif format if true. If false, use ds binary backup.
  # ldif: true

  claimToBackup: data-ds-idrepo-0

  # volumeSnapshotClassName: ds-snapshot-class
  volumeSnapshotClassName: csi-hostpath-snapclass

  # The directory server binary that contains commands to export ldif or run dsbackup
  image: gcr.io/forgeops-public/ds-idrepo/ds-idrepo:dev-temp

  # Secret that contains the ds pem keystore. This is needed to decrypt the data for backup.
  keystore:
    secretName: ds