# Backup to LDIF
apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryBackup
metadata:
  name: ds-backup
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  image:  gcr.io/forgeops-public/ds:7.2-dev
  imagePullPolicy: IfNotPresent

  # The spec for the volume that holds the backup. The volume name will be the same as our metadata.name (ds-backup in this case)
  volumeClaimSpec:
    storageClassName: fast
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 512Mi

  # Backup in ldif format if true (default). If false, use ds binary backup.
  # Currently only ldif is supported.
  # ldif: true

  # The directory pvc to backup. This can be a "live" ds instance,
  # assuming your snapshot provider can take "crash consistent" snapshots
  claimToBackup: data-ds-idrepo-0

  # The snapshot class that will be used when snapshotting the above.
  # volumeSnapshotClassName: ds-snapshot-class
  volumeSnapshotClassName: ds-snapshot-class

  certificates:
    masterSecretName: ds-master-keypair
    sslSecretName: ds-ssl-keypair
    truststoreSecretName: ds-ssl-keypair