apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryRestore
metadata:
  name: ds-restore
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  # The source pvc that holds the ldif backup data to be restored.
  # This is usually the "spec.backupPVC.name" created by a DirectoryBackup job
  sourcePvcName: ds-backup

  # The directory server binary that contains commands to import ldif or run dsbackup
  image:  gcr.io/forgeops-public/ds-idrepo:pem-backup-test

  # Parameters for the pvc that will hold the restored data in DS JE format.
  # The PVC has the name metadata.name (ds-restore in this case).
  volumeClaimSpec:
    storageClassName: csi-hostpath-sc
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 512Mi

  # The class to use when taking volume snapshots. A snapshot named metadata.name will be created.
  volumeSnapshotClassName: csi-hostpath-snapclass

  # Secret that contains the ds pem keystore. This is needed to import data into JE
  # This keystore must match the keystore used to deploy the DirectoryService
  keystore:
    secretName: ds