apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryRestore
metadata:
  name: ds-restore
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  # The source pvc that holds the ldif backup data to be restored.
  # This is usually the "spec.backupPVC.name" created by a DirectoryBackup job
  sourcePvcName: ds-backup

  # The directory server binary that contains commands to import ldif or run dsbackup
  image:  gcr.io/forgeops-public/ds-idrepo:pem-backup-test

  # Parameters for the pvc and snapshot that will hold the restored data in DS JE format.
  # The snapshot can be used as a source for initializing the DS cluster
  # The PVC and the VolumeSnapshsot will both have the same name as this object (ds-restore in this case).

  restore:
    storageClassName: csi-hostpath-sc
    size: 512Mi
    volumeSnapshotClassName: csi-hostpath-snapclass


  # Secret that contains the ds pem keystore. This is needed to import data into JE
  # This keystore must match the keystore used to deploy the DirectoryService
  keystore:
    secretName: ds