# Sample DirectoryService deployment on minikube with the csi hostpath driver
apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryService
metadata:
  name: ds-idrepo
  labels:
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  image: gcr.io/forgeops-public/ds-idrepo:dev
  # The number of DS servers in the topology
  replicas: 1
  # The resources assigned to each DS pod
  resources:
    requests:
      memory: 900Mi
      cpu: 250m
    limits:
      memory: 1024Mi
  # The amount of disk space for directory data
  storage: 1Gi
  # StorageClassName for the persistent volume claim. This should be fast SSD disk for directory server data
  # If the class is not specified, "default" is used. Your cluster
  # must have the default storageClass admission controller enabled to use "standard".
  # The "standard" storageClass is available on minikube, GKE, and EKS
  # storageClassName: standard-rwo
  # For kind testing:
  storageClassName: csi-hostpath-sc


  # Optional: If snapshot name is provided, the directory PVCs will be
  # initialized from the contents of the snapshot. They will NOT be initialized from the
  # "prototype" backends.
  # The name "latest" is reserved. It signifies to the operator
  # to find the name of the latest snapshot that was taken by the operator . If you
  # have a custom volume snapshot (perhaps you manually created a snapshot), use that name instead.
  # initializeFromSnapshotName: "latest"

  # Optional - Configures the operator to automatically take snapshots
  snapshots:
    enabled: false
    # Take a snapshot every 30 minutes
    periodMinutes: 30
    # Keep this many snapshots. Older snapshots will be deleted
    snapshotsRetained: 4
    # This defaults to ds-snapshot-class if not specified
    volumeSnapshotClassName: ds-snapshot-class

  ### Passwords ###
  # Passwords: maps DS accounts to new or existing secrets.
  # The operator supports "bring your own secrets". For example, a secret may have been generated by another operator such as secret agent.
  # A secret that does not set create: true is assumed to be supplied externally. External secrets will not be deleted by the operator
  passwords:
    # uid=admin and uid=monitor are required account secrets.
    uid=admin:
      secretName: ds-passwords
      key: dirmanager.pw
    uid=monitor:
      secretName: ds-passwords
      key: monitor.pw
    # Set the service account passwords
    # We also set the CTS account - in case the user wants to use a single ds instance
    uid=openam_cts,ou=admins,ou=famrecords,ou=openam-session,ou=tokens:
      secretName: ds-env-secrets
      key: AM_STORES_CTS_PASSWORD
    uid=am-identity-bind-account,ou=admins,ou=identities:
      secretName: ds-env-secrets
      key: AM_STORES_USER_PASSWORD
    uid=am-config,ou=admins,ou=am-config:
      secretName: ds-env-secrets
      key: AM_STORES_APPLICATION_PASSWORD
  keystore:
    # The name of the secret that contains the DS keystore
    # The secret must contain at least two keys: keystore and keystore.pin
    # keystore is a pkcs12 Java keystore.
    # Currently the operator can not generate this. Use Secret Agent.
    secretName: ds
  truststore:
    # The name of the secret that contains the truststore PEM certificate. In forgeops this is
    # "platformCA" generated by secret agent operator
    # The secret MUST contain a key "ca.pem" that is the PEM formatted public cert to trust.
    # secretName: "platform-ca"
    secretName: truststore-pem
    # Note: the key name here is hardcoded in the directory server image. It will eventually be configurable
    # keyName: ca.pem


  #### Multi-cluster ####
  # multiCluster:
    ## clusterTopology and clusterIdentifier are required in multi-cluster solutions make DS unique across clusters.
    ## clusterTopology - list of identifiers for the each cluster used to determine the bootstrap servers.
    ## Bootstrap servers example output in a multi-region MCS environment:
    ## Bootstrap replication server(s) : ds-idrepo-0.eu.ds-idrepo-eu.prod.svc.clusterset.local:8989,ds-idrepo-0.us.ds-idrepo.prod.svc.clusterset.local:8989
    # clusterTopology: "eu,us"
    ## clusterIdentifier - current clusters identifier.  Must match 1 of the identifiers in clusterTopology
    # clusterIdentifier: "eu"
    ## Enable MCS(Googles Multi-cluster Services).  Not required for kubedns solution
    # mcsEnabled: true
