apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-ssl-cert
spec:
  # Secret names are always required.
  secretName: ds-ssl-keypair
  secretTemplate:
    labels:
      app: ds-operator

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "forgerock.org"
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: ds
  isCA: false
  privateKey:
    algorithm: ECDSA
    # encoding: PKCS1
    # size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - "*.ds"
  - "*.ds-idrepo"
  - "*.ds-cts"
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
---
# The master keypair used by DS to encrypt data.
# IF YOU LOSE THIS KEYPAIR YOU WILL LOSE YOUR DATA!!!!
# Backup the secret that contains the keypair.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-master-cert
  # namespace: sandbox
spec:
  secretName: ds-master-keypair
  
  secretTemplate:
    labels:
      app: ds-operator

  # Note: The master cert should not be rotated as the private key 
  # must be kept to decrypt the data. You can delete the Certificate
  # and cert-manager will leave the tls secret alone. 
  duration: 1000000h # about 41 years... 
  subject:
    organizations:
      - "ForgeRock.com"
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: "Master Key"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - "*.ds"
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io