kind: Kustomization

resources:
- ds.yaml
- secrets.yaml

generatorOptions:
 disableNameSuffixHash: true

# Generate a configmap with our scripts
configMapGenerator:
- name: ds-script-config
  files:
  # - setup
  - repl-stat.sh
  # - post-init


