#!/usr/bin/env bash
# Sample script to add an index when the server is started

# For now -just exit. 
exit 0

dsconfig --offline --no-prompt --batch <<EOF
create-backend-index \
          --backend-name amIdentityStore \
          --set index-type:equality \
          --index-name carLicense
EOF

rebuild-index  --offline \
 --baseDN ou=identities \
 --index carLicense




# dsconfig --hostname localhost --port 4444 \
#     --bindDN uid=admin --bindPassword $(cat /var/run/secrets/admin/dirmanager.pw) \
#     --trustAll  --no-prompt --batch <<EOF
# create-backend-index \
#           --backend-name amIdentityStore \
#           --set index-type:equality \
#           --index-name carLicense
# EOF



# rebuild-index --hostname localhost --port 4444 \
#     --bindDN uid=admin --bindPassword $(cat /var/run/secrets/admin/dirmanager.pw) \
#     --trustAll   \
#     --baseDN ou=identities \
#     --index carLicense

