name: PullRequest

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build docker image
      shell: bash
      run: |
        make docker

    - name: setup kind
      shell: bash
      run: |
        kind create cluster
        kind load docker-image gcr.io/engineering-devops/ds-operator:latest
        kubectl version

    - name: deploy operator
      shell: bash
      run: |
        make install
        make deploy
        sleep 10
        kubectl -n fr-system get deployment,pods

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
